package com.example.util.network.responsePlayerMatchingHistory

data class PlayInfo(
    val assistCount: Int,
    val attackPoint: Int,
    val backAttackCount: Int,
    val battlePoint: Int,
    val characterId: String,
    val characterName: String,
    val comboCount: Int,
    val damagePoint: Int,
    val deathCount: Int,
    val demolisherKillCount: Int,
    val getCoin: Int,
    val guardTowerKillCount: Int,
    val guardianKillCount: Int,
    val healAmount: Int,
    val killCount: Int,
    val level: Int,
    val maxLifeTime: Int,
    val minLifeTime: Int,
    val partyInfo: List<Any>,
    val partyUserCount: Int,
    val playTime: Int,
    val playTypeName: String,
    val random: Boolean,
    val responseTime: Int,
    val result: String,
    val sentinelKillCount: Int,
    val sightPoint: Int,
    val spellCount: Int,
    val spendCoin: Int,
    val spendConsumablesCoin: Int,
    val towerAttackPoint: Int,
    val trooperKillCount: Int
)